language: c
dist: trusty
env:
  global:
    - VERSION=2.0.0.0 GHCVER=8.0.2 BOOTVER=2.0

matrix:
  include:
    - env: ARCH=i386 OS=linux
      os: linux
      sudo: required
    - env: ARCH=x86_64 OS=linux
      os: linux
      sudo: required
    - env: ARCH=x86_64 OS=osx
      os: osx

install:
 # hvr's PPA
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH
 - export PATH=/opt/cabal/$BOOTVER/bin:$PATH
 - export PATH=/opt/happy/1.19.5/bin:$PATH
 - export PATH=/opt/alex/3.1.7/bin:$PATH
 # Mac OS X GHC install
 - export PATH=$HOME/.ghc-install/$GHCVER/bin:$PATH
 # Mac OS X Cabal install
 - export PATH=$HOME/bin:$PATH
 # Mac OS X Happy install
 - export PATH=$HOME/.cabal/bin:$PATH
 - ./travis-install.sh

script:
 - (cd cabal && cabal new-build -j2 cabal-install:cabal)
 - gzip cabal/dist-newstyle/build/$ARCH-$OS/ghc-$GHCVER/cabal-install-$VERSION/build/cabal/cabal -c > cabal-install-$VERSION-$ARCH-$OS.gz

deploy:
  provider: releases
  api_key:
    secure: xAycwV3aigcb8fQjQMv5Uvf5IC76BmuR9U3ZkOZznuILGQSzGR/j3MT+qqnysPKs2LhCFaiRlDNsXkKc5oes44RFJul8eB3cBMDu8N/weIz96Nc6BSOp7rY7ffoRMcSX6csJ5EKCxlHazuYXxoEUwUjmE53qCj0hVZmanx+ulynlZfQzTuKU76HggeKBKSAfjZKTmz4RI7KJ86foZYBef9RAbSks87cCmWNo5ylLPqrTj32lSD2gEfuLlwW6K3UzKmqQ1AZ8bbJvtqyi0xqZ/dS+OwIAZLdhBIU7qvBx5SRuu0QvxLuBjfRPdr1j7+yTEmZMLdlJ0N4PWvNwRfJnN5QMT4lBaXG8wpb2MXeVXC4u8RwtjeQu/S/2TGDDdZJEPHoDIRlq2PIQ0hPSUIN9QN4iUfn/kMAM7gqHhUehkM0z79u8JGCiMX84MwGMGA6eJ3Y0Rco7rNzWtvu1lctngLOglMChhlBwrmqtn1BT5LgUo84ljGqyWc+ieYiL53+xV1RsWEKL3qEH9bYgbeK6YoqVJqe+NSA3eoHyK11Lnq4mCKPAA/o7oE8Y4vJqP/sKksb47k0xLTNuUYJol42m7mWl6HvdDdKfhC4RBO6J9BptZjaJ+q9Sd8ijCzhAZlEOFq2OcNxKmDRM0IQRHC5It8NlD5ZN2iIXRxIGTXtG1iQ=
  skip_cleanup: true
  file: cabal-install-$VERSION-$ARCH-$OS.gz
  on:
    tags: true
