language: c
dist: trusty
env:
  global:
    - VERSION=2.0.0.0 GHCVER=8.0.2 BOOTVER=2.0

matrix:
  include:
    - env: ARCH=i386 OS=linux
      os: linux
      sudo: required
    - env: ARCH=x86_64 OS=linux
      os: linux
      sudo: required
    - env: ARCH=x86_64 OS=osx
      os: osx

script:
 - ./travis-release.sh

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_DEPLOY_API_KEY
  skip_cleanup: true
  file: cabal-install-$VERSION-$ARCH-$OS.gz
  on:
    tags: true
